FROM python:3.10-slim  

WORKDIR /app/backend  

COPY requirements.txt .  
RUN pip install --no-cache-dir -r requirements.txt  

# Копируем ВЕСЬ проект (включая статику)
COPY . .


CMD ["sh", "-c", "uvicorn main:app --host 0.0.0.0 --port 8081 & sleep 5 && python create_users.py && wait"]
